from enum import StrEnum


class ActionType(StrEnum):
    ASK_HISTORY = "ASK_HISTORY"
    EXAM = "EXAM"
    TEST = "TEST"
    CONSULT = "CONSULT"
    TRANSFER = "TRANSFER"
    TREATMENT = "TREATMENT"
    PROCEDURE = "PROCEDURE"
    PATHOLOGY = "PATHOLOGY"
    REASSESS = "REASSESS"
    DISCHARGE_FOLLOWUP = "DISCHARGE_FOLLOWUP"
