"use client";

import { Pause, Play, RotateCcw, SkipBack, SkipForward } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { DemoCase, ReplayStatus, TraceEvent } from "@/lib/demo/types";

type Props = { caseData: DemoCase; activeStepId: string; finalizedStepIds: string[]; status: ReplayStatus; cursor: number; speed: number; currentEvent?: TraceEvent; play: () => void; pause: () => void; next: () => void; previous: () => void; restart: () => void; onSelectStep: (id: string) => void; setSpeed: (speed: number) => void };

export function ReplayControls(props: Props) {
  const { caseData, activeStepId, status, cursor, speed, currentEvent, play, pause, next, previous, restart, onSelectStep, setSpeed, finalizedStepIds } = props;
  return <section className="replay-panel panel" aria-label="Replay controls">
    <div className="replay-timeline"><span className="timeline-label">DECISION TIMELINE</span><div className="step-timeline">{caseData.nodes.map(step => <button key={step.stepId} className={`timeline-step ${activeStepId === step.stepId ? "timeline-active" : ""} ${finalizedStepIds.includes(step.stepId) ? "timeline-completed" : ""}`} onClick={() => onSelectStep(step.stepId)} aria-label={`Go to ${step.stepId}: ${step.title}`} aria-current={activeStepId === step.stepId ? "step" : undefined} title={`${step.stepId} · ${step.title}`}><span /><small>{step.stepId}</small></button>)}</div><span className="timeline-end">{caseData.nodes.length} steps</span></div>
    <div className="replay-control-row"><div className="transport"><Button variant="ghost" size="icon" onClick={restart} disabled={cursor < 0} aria-label="Restart replay" title="Restart (R)"><RotateCcw size={15} /></Button><Button variant="ghost" size="icon" onClick={previous} disabled={cursor < 0} aria-label="Previous step" title="Previous step (←)"><SkipBack size={16} /></Button><Button onClick={status === "playing" ? pause : play} className="play-button" aria-label={status === "playing" ? "Pause replay" : status === "completed" ? "Replay again" : "Play replay"}>{status === "playing" ? <Pause size={15} fill="currentColor" /> : <Play size={15} fill="currentColor" />}{status === "playing" ? "Pause" : status === "completed" ? "Replay" : "Play replay"}</Button><Button variant="ghost" size="icon" onClick={next} disabled={status === "completed"} aria-label="Next step" title="Next step (→)"><SkipForward size={16} /></Button><div className="speed-control"><label className="sr-only" htmlFor="replay-speed">Replay speed</label><select id="replay-speed" value={speed} onChange={event => setSpeed(Number(event.target.value))}><option value={0.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select></div></div><div className="current-event"><span className={`status-dot ${status === "playing" ? "is-live" : ""}`} /><p>{currentEvent?.summary ?? "Press play to follow the first decision."}</p></div><div className="trace-count"><span>{Math.max(0, cursor + 1).toString().padStart(3, "0")}</span> / {caseData.events.length} events</div></div>
  </section>;
}
